/**
 * PetPal API
 * Pet Sitter Search App documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {UserResponse} from './userResponse';
import {ReviewsInfo} from './reviewsInfo';
import {ContactInfo} from './contactInfo';


export interface MeResponse {
    bio?: string | null;
    readonly user: UserResponse;
    contact: ContactInfo;
    readonly is_pet_sitter: boolean;
    readonly reviews: ReviewsInfo;
}

