/**
 * PetPal API
 * Pet Sitter Search App documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {MeResponse} from './meResponse';
import {PetExperienceEnum} from './petExperienceEnum';


export interface PetSitterResponse {
    profile: MeResponse;
    experience?: string | null;
    pet_experience: Array<PetExperienceEnum>;
    motivation?: string | null;
    availability_start_date: string;
    availability_end_date: string;
}

