/**
 * PetPal API
 * Pet Sitter Search App documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PetsInvolvedEnum = 'DOG' | 'CAT' | 'HORSE' | 'BIRD' | 'OTHER' | 'SMALL_PET';

export const PetsInvolvedEnum = {
    Dog: 'DOG' as PetsInvolvedEnum,
    Cat: 'CAT' as PetsInvolvedEnum,
    Horse: 'HORSE' as PetsInvolvedEnum,
    Bird: 'BIRD' as PetsInvolvedEnum,
    Other: 'OTHER' as PetsInvolvedEnum,
    SmallPet: 'SMALL_PET' as PetsInvolvedEnum
};

