/**
 * PetPal API
 * Pet Sitter Search App documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {MeResponse} from './meResponse';


export interface ProfilePageResponse {
    profiles: Array<MeResponse>;
    pageSize: number;
    pagesTotal: number;
    pageIndex: number;
    length: number;
}

