/**
 * PetPal API
 * Pet Sitter Search App documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MeResponse } from './meResponse';
import { PetsInvolvedEnum } from './petsInvolvedEnum';


export interface ReviewResponse { 
    reviewer: MeResponse;
    pets_involved: Array<PetsInvolvedEnum>;
    score?: number;
    description?: string;
    date?: string;
}

