/**
 * PetPal API
 * Pet Sitter Search App documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PetsInvolvedEnum } from './petsInvolvedEnum';


export interface ReviewRequest { 
    pets_involved: Array<PetsInvolvedEnum>;
    score?: number;
    description?: string;
}

