export * from './api.service';
import { ApiService } from './api.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './petSitters.service';
import { PetSittersService } from './petSitters.service';
export * from './profile.service';
import { ProfileService } from './profile.service';
export * from './reviews.service';
import { ReviewsService } from './reviews.service';
export const APIS = [ApiService, AuthService, PetSittersService, ProfileService, ReviewsService];
