# Generated by Django 3.2.7 on 2021-11-17 22:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pet_sitters', '0002_alter_sitter_pet_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='pet_experience',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DOG', 'DOG'), ('CAT', 'CAT'), ('HORSE', 'HORSE'), ('BIRD', 'BIRD'), ('OTHER', 'OTHER'), ('SMALL_PET', 'SMALL_PET')], max_length=34, null=True),
        ),
    ]
