# Generated by Django 3.2.7 on 2021-10-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211025_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_pet_owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pet_sitter',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
